### ISSUE TITLE
Error running generate.py

### ISSUE THREAD

**Issue by joshtemple** [smart-on-fhir/sample-patients-stu3#4]
I'm getting the following error when I run `generate.py` using Python 2.7 in a fresh Conda virtual environment:
```
python generate.py --write-fhir ../out
```
Traceback:
```
Writing files to ../out:
Traceback (most recent call last):
  File "generate.py", line 121, in <module>
    fhir.FHIRSamplePatient(pid, path, baseURL).writePatientData(prefix)
  File "/Users/josh.temple/personal/sample-patients-stu3/bin/fhir.py", line 495, in writePatientData
    self.add_practitioners(prefix)
  File "/Users/josh.temple/personal/sample-patients-stu3/bin/fhir.py", line 333, in add_practitioners
    "entry": [ o.toJSON(prefix) ]
  File "/Users/josh.temple/personal/sample-patients-stu3/bin/practitioner.py", line 46, in toJSON
    "url": "Practitioner/" + prefix + "Practitioner-" + data["id"]
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by vlad-ignatov** [comment]
Thanks for reporting this. What if also add the `--id-prefix` option as in the example in the readme? Does that work for you?
